// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJX-WC4YIqJMCITD4cYBsrHCXFELja4c',
    appId: '1:242312898594:web:d1d99b6227d42f4e97827b',
    messagingSenderId: '242312898594',
    projectId: 'citric-glow-386318',
    authDomain: 'citric-glow-386318.firebaseapp.com',
    databaseURL: 'https://citric-glow-386318-default-rtdb.firebaseio.com',
    storageBucket: 'citric-glow-386318.appspot.com',
    measurementId: 'G-YEN753NEWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_XdhFzqCwU6y-XkHvOhu7oh_ElzzhAsE',
    appId: '1:242312898594:android:99343d01855f7ec197827b',
    messagingSenderId: '242312898594',
    projectId: 'citric-glow-386318',
    databaseURL: 'https://citric-glow-386318-default-rtdb.firebaseio.com',
    storageBucket: 'citric-glow-386318.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBySpqE74eMyMJ5Y5CLlg7Dp1YHHQdFPVs',
    appId: '1:242312898594:ios:148735d6d4c46da597827b',
    messagingSenderId: '242312898594',
    projectId: 'citric-glow-386318',
    databaseURL: 'https://citric-glow-386318-default-rtdb.firebaseio.com',
    storageBucket: 'citric-glow-386318.appspot.com',
    iosClientId: '242312898594-l3hgkcr7stdn1purf5t83vi0kr3errng.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBySpqE74eMyMJ5Y5CLlg7Dp1YHHQdFPVs',
    appId: '1:242312898594:ios:7c9d5fd7e0e27b2497827b',
    messagingSenderId: '242312898594',
    projectId: 'citric-glow-386318',
    databaseURL: 'https://citric-glow-386318-default-rtdb.firebaseio.com',
    storageBucket: 'citric-glow-386318.appspot.com',
    iosClientId: '242312898594-2fnidjgd6keb51mniiuhagpc08il9ad3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameSpot.RunnerTests',
  );
}
